branches:
 only:
  - master
  - /^[0-9]+(\.[0-9]+)*(\.post[0-9]+)?$/

language: python

matrix:
  include:

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.7.0

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.6.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.5.5

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=3.4.8

    - os: osx
      language: generic
      env:
        - PYTHON_VERSION=2.7.15

cache:
  directories:
    - $HOME/.pyenv/versions/3.7.0
    - $HOME/.pyenv/versions/3.6.5
    - $HOME/.pyenv/versions/3.5.5
    - $HOME/.pyenv/versions/3.4.8
    - $HOME/.pyenv/versions/2.7.15
    - $HOME/downloads

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mkdir $HOME/bin; ln -s $(which pip2) $HOME/bin/pip; ln -s $(which python2) $HOME/bin/python; fi
  - python -m pip install --disable-pip-version-check --upgrade pip
  - pip install -U scikit-ci scikit-ci-addons
  - ci_addons --install ../addons

install:
  - ci install

script:
  - ci test

after_success:
  - ci after_test

deploy:
  # deploy-release
  - provider: script
    script: pwd && ls dist;echo "deploy-release" && ~/.pyenv/versions/${PYTHON_VERSION}/bin/twine upload -u $PYPI_USER -p $PYPI_PASSWORD --repository-url https://test.pypi.org/legacy/ --skip-existing dist/*
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      tags: true
  # deploy-master
  - provider: script
    script: pwd && ls dist;echo "deploy-master" && echo "not implemented"
    skip_cleanup: true
    on:
      repo: ${TRAVIS_REPO_SLUG}
      branch: master

env:
  global:
    # PYPI_USER
    - secure: "TvDSEYePMmeOoYOGSQrVpA+molgOk+ZnV+J45RCG2h9RP6773SBJ7UVKN+otlVV4EuWQiZP1ptDhFQS4HrMBZAR1ERRIYn8z5MqP/r+gd6knZ7v77pIYWeKiNHRIsuuRixDDACD6Zn5lZLLZj0MuJu4pSz7SCNMtrPLv/fC1Upg="
    # PYPI_PASSWORD
    - secure: "Bvo8KCBtMUuliB7chzFZTEs00O7dGh9Y7myu6SmbTBxw4ECi7COCWSsz9j2rSsMQefGG6jJmY9nJo8jOXFTNDQ7OZYiOIDCgRY6FXa9dJALi/O7QqPhgjujzrhNbGnoEBJqIG4Ib9PqMfewS65VDMiOzAfNM9qYc9ARBQGl4YZY="
