package:
  name: wordcloud
  version: "1.4.1"

source:
  path: ../

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
    - python
    - pip

  run:
    - python
    - numpy >=1.6.1
    - pillow

test:
  imports:
    - wordcloud
  commands:
    - wordcloud_cli.py --help

about:
  home: https://github.com/amueller/word_cloud
  license: MIT
  summary: A little word cloud generator in Python
